# Generated by Django 6.0.3 on 2026-03-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='languages_tools',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='tagline',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
