# Generated by Django 6.0.3 on 2026-03-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_profil_education_profil_introduction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='description',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='education',
            new_name='education_summary',
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='twitter',
            new_name='facebook',
        ),
        migrations.AddField(
            model_name='profil',
            name='projects_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='twitter_x',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='youtube',
            field=models.URLField(blank=True),
        ),
    ]
